global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'order-gateway-grpc'
    static_configs:
      - targets: ['order-gateway:8080']

  - job_name: 'order-processor-grpc'
    static_configs:
      - targets: ['order-processor:8080']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']